version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    open-pull-requests-limit: 20
    schedule:
      interval: daily
    groups:
      allMinorPatch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily